@extends('panel.layouts.app')
@section('title','Diet Templates')
@section('content')
{{-- Full AJAX CRUD + live search: no alert, confirm or reload. --}}
<div class="d-flex justify-content-between align-items-center mb-4"><div><h4 class="mb-1">Diet Templates</h4><p class="text-muted mb-0">Reusable meal plans for your gym.</p></div><button class="btn btn-primary" id="createBtn">+ Create Template</button></div>
<div class="card mb-3"><div class="card-body"><input id="dietSearch" class="form-control" placeholder="Search template, goal or diet type..."></div></div>
<div class="row g-3" id="dietGrid"></div>
<div class="modal fade" id="dietModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form id="dietForm"><div class="modal-header"><h5 id="modalTitle">Create Diet Template</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-2"><div class="col-md-6"><input class="form-control" name="title" placeholder="Template title" required></div><div class="col-md-3"><input class="form-control" name="goal" placeholder="Goal"></div><div class="col-md-3"><input class="form-control" name="diet_type" placeholder="Diet type"></div><div class="col-md-4"><input class="form-control" type="number" name="daily_calories" placeholder="Calories"></div><div class="col-md-4"><input class="form-control" type="number" name="protein_target" placeholder="Protein g"></div><div class="col-md-4"><input class="form-control" type="number" name="water_target" placeholder="Water ml"></div><div class="col-12"><textarea class="form-control" name="general_instructions" placeholder="General instructions"></textarea></div></div><hr><div class="d-flex justify-content-between"><h6>Meals</h6><button type="button" class="btn btn-sm btn-outline-secondary" id="addMeal">+ Add Meal</button></div><div id="mealRows"></div></div><div class="modal-footer"><button class="btn btn-primary" id="saveDiet">Save Template</button></div></form></div></div></div>
@endsection
@push('scripts')
<script>
const templates=@json($templates);let editing=null;let mealIndex=0;const grid=document.getElementById('dietGrid'),form=document.getElementById('dietForm'),rows=document.getElementById('mealRows'),modal=new bootstrap.Modal(document.getElementById('dietModal')),csrf=document.querySelector('meta[name=csrf-token]').content;
const toast=(m,t='success')=>window.showToast?window.showToast(m,t):console.log(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function card(t){return `<div class="col-md-6 diet-card" data-search="${esc(t.title+' '+(t.goal||'')+' '+(t.diet_type||'')).toLowerCase()}"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><h5>${esc(t.title)}</h5><small class="text-muted">${esc(t.goal||'General')} · ${(t.meals||[]).length} meals</small></div><div><button class="btn btn-sm btn-outline-primary" onclick="editDiet(${t.id})">Edit</button> <button class="btn btn-sm btn-outline-danger" onclick="deleteDiet(${t.id})">Delete</button></div></div>${t.general_instructions?`<p class="mt-3 mb-2">${esc(t.general_instructions)}</p>`:''}<ul class="list-group list-group-flush">${(t.meals||[]).map(m=>`<li class="list-group-item px-0"><b>${esc(m.meal_time||'')}</b> ${esc(m.meal_name)}<br><small class="text-muted">${esc(m.food_items||'')} ${esc(m.quantity||'')}</small></li>`).join('')}</ul></div></div></div>`}
function render(){grid.innerHTML=templates.length?templates.map(card).join(''):'<div class="col-12 text-center text-muted py-5">No diet templates found.</div>';filter();}
function filter(){const q=document.getElementById('dietSearch').value.toLowerCase();document.querySelectorAll('.diet-card').forEach(c=>c.style.display=c.dataset.search.includes(q)?'':'none');}
function meal(m={}){const i=mealIndex++;rows.insertAdjacentHTML('beforeend',`<div class="row g-2 mb-2 meal"><div class="col-2"><input class="form-control" name="meals[${i}][meal_time]" placeholder="Time" value="${esc(m.meal_time||'')}"></div><div class="col-3"><input class="form-control" name="meals[${i}][meal_name]" placeholder="Meal name" required value="${esc(m.meal_name||'')}"></div><div class="col-4"><input class="form-control" name="meals[${i}][food_items]" placeholder="Food items" value="${esc(m.food_items||'')}"></div><div class="col-2"><input class="form-control" name="meals[${i}][quantity]" placeholder="Quantity" value="${esc(m.quantity||'')}"></div><div class="col-1"><button type="button" class="btn btn-outline-danger" onclick="this.closest('.meal').remove()">×</button></div></div>`)}
function openDiet(t=null){editing=t;form.reset();rows.innerHTML='';mealIndex=0;document.getElementById('modalTitle').textContent=t?'Edit Diet Template':'Create Diet Template';if(t){['title','goal','diet_type','daily_calories','protein_target','water_target','general_instructions'].forEach(k=>form.elements[k].value=t[k]??'');(t.meals||[]).forEach(meal)}else meal();modal.show()}
window.editDiet=id=>openDiet(templates.find(t=>t.id==id));window.deleteDiet=async id=>{try{const r=await fetch(`{{ url('/panel/diets') }}/${id}`,{method:'DELETE',headers:{'X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}),d=await r.json();if(!r.ok||!d.success)throw Error(d.error);templates.splice(templates.findIndex(t=>t.id==id),1);render();toast(d.message)}catch(e){toast(e.message||'Could not delete template','error')}};
document.getElementById('createBtn').onclick=()=>openDiet();document.getElementById('addMeal').onclick=()=>meal();document.getElementById('dietSearch').oninput=filter;form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),url=editing?`{{ url('/panel/diets') }}/${editing.id}`:`{{ route('panel.diets.store') }}`;if(editing)fd.append('_method','PUT');try{const r=await fetch(url,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},body:fd}),d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'Could not save template');if(editing)templates[templates.findIndex(t=>t.id==editing.id)]=d.template;else templates.unshift(d.template);modal.hide();render();toast(d.message)}catch(x){toast(x.message||'Could not save template','error')}};render();
</script>
@endpush
