import 'package:flutter/material.dart';
import 'package:gymxbook/core/widgets/ui.dart';

// UX Batch 1: read-only Diet Template detail view.
class DietTemplateDetailScreen extends StatelessWidget {
  final Map<String,dynamic> template;
  final VoidCallback? onEdit;
  const DietTemplateDetailScreen({super.key,required this.template,this.onEdit});
  @override Widget build(BuildContext context){final meals=(template['meals'] as List?)??[];return Scaffold(appBar:AppBar(title:Text(template['title']??'Diet Template'),actions:[if(onEdit!=null)IconButton(onPressed:onEdit,icon:const Icon(Icons.edit_rounded))]),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:AppTheme.darkHeroGradient,borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(template['title']??'',style:context.typo.titleLarge?.copyWith(color:Colors.white)),const SizedBox(height:6),Text(template['goal']??'General Diet',style:context.typo.bodyMedium?.copyWith(color:Colors.white70)),const SizedBox(height:14),Wrap(spacing:8,children:[if(template['daily_calories']!=null)_chip('${template['daily_calories']} kcal'),if(template['protein_target']!=null)_chip('${template['protein_target']}g protein'),if(template['water_target']!=null)_chip('${template['water_target']} ml water')])])),const SizedBox(height:18),Text('Meals',style:context.typo.titleLarge),...meals.map((e){final m=Map<String,dynamic>.from(e);return Padding(padding:const EdgeInsets.only(top:10),child:SurfaceCard(child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[IconBadge(Icons.restaurant_rounded,color:AppTheme.success,size:38),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m['meal_name']??'',style:context.typo.titleSmall),if((m['meal_time']??'').toString().isNotEmpty)Text(m['meal_time'],style:context.typo.bodySmall?.copyWith(color:AppTheme.brand)),if((m['food_items']??'').toString().isNotEmpty)Padding(padding:const EdgeInsets.only(top:4),child:Text(m['food_items'],style:context.typo.bodyMedium)),if((m['quantity']??'').toString().isNotEmpty)Text(m['quantity'],style:context.typo.bodySmall?.copyWith(color:context.tokens.textTertiary)),if((m['notes']??'').toString().isNotEmpty)Text(m['notes'],style:context.typo.bodySmall?.copyWith(color:context.tokens.textTertiary))]))])));}),if((template['general_instructions']??'').toString().isNotEmpty)...[const SizedBox(height:18),Text('Instructions',style:context.typo.titleLarge),const SizedBox(height:8),SurfaceCard(child:Text(template['general_instructions'],style:context.typo.bodyMedium))]]));}
  Widget _chip(String s)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:Colors.white24,borderRadius:BorderRadius.circular(16)),child:Text(s,style:const TextStyle(color:Colors.white,fontSize:11)));
}
